-- MySQL Script generated by MySQL Workbench
-- Tue Sep 30 12:57:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PAI1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PAI1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PAI1` ;
USE `PAI1` ;

-- -----------------------------------------------------
-- Table `PAI1`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI1`.`Usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Salt` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAI1`.`Transferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI1`.`Transferencias` (
  `id` INT NOT NULL,
  `Cuenta Origen` INT NULL,
  `Cuenta Destino` INT NULL,
  `Cantidad Transferida` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAI1`.`Nonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAI1`.`Nonce` (
  `id` INT NOT NULL,
  `HASH-NONCE` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
